/**
 * Common series patterns to detect
 */

import { PUBLISHERS } from "./publishersPatterns.js";

export const SERIES_PATTERNS = [
    // DC Comics
    { pattern: /batman/i, series: "Batman", publisher: PUBLISHERS.DC },
    { pattern: /superman/i, series: "Superman", publisher: PUBLISHERS.DC },
    { pattern: /wonder\s*woman/i, series: "Wonder Woman", publisher: PUBLISHERS.DC },
    { pattern: /flash/i, series: "The Flash", publisher: PUBLISHERS.DC },
    { pattern: /green\s*lantern/i, series: "Green Lantern", publisher: PUBLISHERS.DC },
    { pattern: /aquaman/i, series: "Aquaman", publisher: PUBLISHERS.DC },
    { pattern: /justice\s*league/i, series: "Justice League", publisher: PUBLISHERS.DC },
    { pattern: /watchmen/i, series: "Watchmen", publisher: PUBLISHERS.DC },
    { pattern: /nightwing/i, series: "Nightwing", publisher: PUBLISHERS.DC },
    { pattern: /harley\s*quinn/i, series: "Harley Quinn", publisher: PUBLISHERS.DC },
    { pattern: /suicide\s*squad/i, series: "Suicide Squad", publisher: PUBLISHERS.DC },
    { pattern: /teen\s*titans/i, series: "Teen Titans", publisher: PUBLISHERS.DC },
    { pattern: /green\s*arrow/i, series: "Green Arrow", publisher: PUBLISHERS.DC },
    { pattern: /cyborg/i, series: "Cyborg", publisher: PUBLISHERS.DC },
    { pattern: /shazam/i, series: "Shazam", publisher: PUBLISHERS.DC },
    { pattern: /Constantine/i, series: "Constantine", publisher: PUBLISHERS.DC },
    { pattern: /swamp\s*thing/i, series: "Swamp Thing", publisher: PUBLISHERS.DC },
    { pattern: /birds\s*of\s*prey/i, series: "Birds of Prey", publisher: PUBLISHERS.DC },
    { pattern: /batgirl/i, series: "Batgirl", publisher: PUBLISHERS.DC },
    { pattern: /supergirl/i, series: "Supergirl", publisher: PUBLISHERS.DC },
    { pattern: /lobo/i, series: "Lobo", publisher: PUBLISHERS.DC },
    { pattern: /doom\s*patrol/i, series: "Doom Patrol", publisher: PUBLISHERS.DC },
    { pattern: /jonah\s*hex/i, series: "Jonah Hex", publisher: PUBLISHERS.DC },

    // Marvel
    { pattern: /spider[-\s]?man/i, series: "Spider-Man", publisher: PUBLISHERS.MARVEL },
    { pattern: /amazing\s*spider[-\s]?man/i, series: "Amazing Spider-Man", publisher: PUBLISHERS.MARVEL },
    { pattern: /ultimate\s*spider[-\s]?man/i, series: "Ultimate Spider-Man", publisher: PUBLISHERS.MARVEL },
    { pattern: /x[-\s]?men/i, series: "X-Men", publisher: PUBLISHERS.MARVEL },
    { pattern: /uncanny\s*x[-\s]?men/i, series: "Uncanny X-Men", publisher: PUBLISHERS.MARVEL },
    { pattern: /avengers/i, series: "Avengers", publisher: PUBLISHERS.MARVEL },
    { pattern: /iron\s*man/i, series: "Iron Man", publisher: PUBLISHERS.MARVEL },
    { pattern: /captain\s*america/i, series: "Captain America", publisher: PUBLISHERS.MARVEL },
    { pattern: /thor\b/i, series: "Thor", publisher: PUBLISHERS.MARVEL },
    { pattern: /hulk/i, series: "Hulk", publisher: PUBLISHERS.MARVEL },
    { pattern: /incredible\s*hulk/i, series: "Incredible Hulk", publisher: PUBLISHERS.MARVEL },
    { pattern: /daredevil/i, series: "Daredevil", publisher: PUBLISHERS.MARVEL },
    { pattern: /deadpool/i, series: "Deadpool", publisher: PUBLISHERS.MARVEL },
    { pattern: /wolverine/i, series: "Wolverine", publisher: PUBLISHERS.MARVEL },
    { pattern: /fantastic\s*four/i, series: "Fantastic Four", publisher: PUBLISHERS.MARVEL },
    { pattern: /star\s*wars/i, series: "Star Wars", publisher: PUBLISHERS.MARVEL },
    { pattern: /punisher/i, series: "The Punisher", publisher: PUBLISHERS.MARVEL },
    { pattern: /black\s*panther/i, series: "Black Panther", publisher: PUBLISHERS.MARVEL },
    { pattern: /doctor\s*strange/i, series: "Doctor Strange", publisher: PUBLISHERS.MARVEL },
    { pattern: /guardians\s*of\s*the\s*galaxy/i, series: "Guardians of the Galaxy", publisher: PUBLISHERS.MARVEL },
    { pattern: /black\s*widow/i, series: "Black Widow", publisher: PUBLISHERS.MARVEL },
    { pattern: /hawkeye/i, series: "Hawkeye", publisher: PUBLISHERS.MARVEL },
    { pattern: /ant[-\s]?man/i, series: "Ant-Man", publisher: PUBLISHERS.MARVEL },
    { pattern: /ms\s*marvel|kamala\s*khan/i, series: "Ms. Marvel", publisher: PUBLISHERS.MARVEL },
    { pattern: /moon\s*knight/i, series: "Moon Knight", publisher: PUBLISHERS.MARVEL },
    { pattern: /ghost\s*rider/i, series: "Ghost Rider", publisher: PUBLISHERS.MARVEL },
    { pattern: /blade/i, series: "Blade", publisher: PUBLISHERS.MARVEL },
    { pattern: /silver\s*surfer/i, series: "Silver Surfer", publisher: PUBLISHERS.MARVEL },
    { pattern: /she[-\s]?hulk/i, series: "She-Hulk", publisher: PUBLISHERS.MARVEL },
    { pattern: /venom/i, series: "Venom", publisher: PUBLISHERS.MARVEL },
    { pattern: /carnage/i, series: "Carnage", publisher: PUBLISHERS.MARVEL },
    { pattern: /new\s*mutants/i, series: "New Mutants", publisher: PUBLISHERS.MARVEL },
    { pattern: /x[-\s]?force/i, series: "X-Force", publisher: PUBLISHERS.MARVEL },
    { pattern: /elektra/i, series: "Elektra", publisher: PUBLISHERS.MARVEL },
    { pattern: /scarlet\s*witch/i, series: "Scarlet Witch", publisher: PUBLISHERS.MARVEL },
    { pattern: /vision/i, series: "Vision", publisher: PUBLISHERS.MARVEL },
    { pattern: /loki/i, series: "Loki", publisher: PUBLISHERS.MARVEL },

    // Image Comics
    { pattern: /walking\s*dead/i, series: "The Walking Dead", publisher: PUBLISHERS.IMAGE },
    { pattern: /spawn/i, series: "Spawn", publisher: PUBLISHERS.IMAGE },
    { pattern: /invincible/i, series: "Invincible", publisher: PUBLISHERS.IMAGE },
    { pattern: /saga\b/i, series: "Saga", publisher: PUBLISHERS.IMAGE },
    { pattern: /savage\s*dragon/i, series: "Savage Dragon", publisher: PUBLISHERS.IMAGE },
    { pattern: /witchblade/i, series: "Witchblade", publisher: PUBLISHERS.IMAGE },
    { pattern: /darkness/i, series: "The Darkness", publisher: PUBLISHERS.IMAGE },
    { pattern: /bone/i, series: "Bone", publisher: PUBLISHERS.IMAGE },
    { pattern: /chew/i, series: "Chew", publisher: PUBLISHERS.IMAGE },
    { pattern: /east\s*of\s*west/i, series: "East of West", publisher: PUBLISHERS.IMAGE },
    { pattern: /paper\s*girls/i, series: "Paper Girls", publisher: PUBLISHERS.IMAGE },
    { pattern: /monstress/i, series: "Monstress", publisher: PUBLISHERS.IMAGE },
    { pattern: /lazarus/i, series: "Lazarus", publisher: PUBLISHERS.IMAGE },
    { pattern: /descender/i, series: "Descender", publisher: PUBLISHERS.IMAGE },
    { pattern: /ascender/i, series: "Ascender", publisher: PUBLISHERS.IMAGE },
    { pattern: /deadly\s*class/i, series: "Deadly Class", publisher: PUBLISHERS.IMAGE },
    { pattern: /low/i, series: "Low", publisher: PUBLISHERS.IMAGE },
    { pattern: /morning\s*glories/i, series: "Morning Glories", publisher: PUBLISHERS.IMAGE },
    { pattern: /outcast/i, series: "Outcast", publisher: PUBLISHERS.IMAGE },

    // Dark Horse
    { pattern: /hellboy/i, series: "Hellboy", publisher: PUBLISHERS.DARK_HORSE },
    { pattern: /sin\s*city/i, series: "Sin City", publisher: PUBLISHERS.DARK_HORSE },
    { pattern: /300/i, series: "300", publisher: PUBLISHERS.DARK_HORSE },
    { pattern: /umbrella\s*academy/i, series: "The Umbrella Academy", publisher: PUBLISHERS.DARK_HORSE },
    { pattern: /aliens/i, series: "Aliens", publisher: PUBLISHERS.DARK_HORSE },
    { pattern: /predator/i, series: "Predator", publisher: PUBLISHERS.DARK_HORSE },
    { pattern: /b\.?p\.?r\.?d/i, series: "B.P.R.D.", publisher: PUBLISHERS.DARK_HORSE },
    { pattern: /usagi\s*yojimbo/i, series: "Usagi Yojimbo", publisher: PUBLISHERS.DARK_HORSE },

    // Vertigo/DC Black Label
    { pattern: /sandman/i, series: "Sandman", publisher: PUBLISHERS.VERTIGO },
    { pattern: /preacher/i, series: "Preacher", publisher: PUBLISHERS.VERTIGO },
    { pattern: /fables/i, series: "Fables", publisher: PUBLISHERS.VERTIGO },
    { pattern: /y\s*the\s*last\s*man|y:\s*the\s*last\s*man/i, series: "Y: The Last Man", publisher: PUBLISHERS.VERTIGO },
    { pattern: /transmetropolitan/i, series: "Transmetropolitan", publisher: PUBLISHERS.VERTIGO },
    { pattern: /lucifer/i, series: "Lucifer", publisher: PUBLISHERS.VERTIGO },
    { pattern: /100\s*bullets/i, series: "100 Bullets", publisher: PUBLISHERS.VERTIGO },
    { pattern: /hellblazer/i, series: "Hellblazer", publisher: PUBLISHERS.VERTIGO },
    { pattern: /animal\s*man/i, series: "Animal Man", publisher: PUBLISHERS.VERTIGO },

    // IDW
    { pattern: /tmnt|teenage\s*mutant/i, series: "Teenage Mutant Ninja Turtles", publisher: PUBLISHERS.IDW },
    { pattern: /transformers/i, series: "Transformers", publisher: PUBLISHERS.IDW },
    { pattern: /judge\s*dredd/i, series: "Judge Dredd", publisher: PUBLISHERS.IDW },
    { pattern: /locke\s*&\s*key|locke\s*and\s*key/i, series: "Locke & Key", publisher: PUBLISHERS.IDW },
    { pattern: /g\.?i\.?\s*joe/i, series: "G.I. Joe", publisher: PUBLISHERS.IDW },

    // BOOM! Studios
    { pattern: /mouse\s*guard/i, series: "Mouse Guard", publisher: PUBLISHERS.BOOM },
    { pattern: /lumberjanes/i, series: "Lumberjanes", publisher: PUBLISHERS.BOOM },
    { pattern: /something\s*is\s*killing\s*the\s*children/i, series: "Something is Killing the Children", publisher: PUBLISHERS.BOOM },
    { pattern: /once\s*&\s*future/i, series: "Once & Future", publisher: PUBLISHERS.BOOM },

    // Valiant
    { pattern: /bloodshot/i, series: "Bloodshot", publisher: PUBLISHERS.VALIANT },
    { pattern: /harbinger/i, series: "Harbinger", publisher: PUBLISHERS.VALIANT },
    { pattern: /x-o\s*manowar/i, series: "X-O Manowar", publisher: PUBLISHERS.VALIANT },
    { pattern: /ninjak/i, series: "Ninjak", publisher: PUBLISHERS.VALIANT },

    // Other Publishers
    { pattern: /speed\s*racer/i, series: "Speed Racer", publisher: PUBLISHERS.MAD_CAVE },
    { pattern: /brzrkr|berzerker/i, series: "BRZRKR", publisher: PUBLISHERS.BOOM },
    { pattern: /godzilla.*kai\s*sei\s*era|kai\s*sei\s*era/i, series: "Godzilla (Kai Sei Era)", publisher: PUBLISHERS.IDW },
    { pattern: /godzilla.*kai\s*sei|kai\s*sei/i, series: "Godzilla (Kai Sei Era)", publisher: PUBLISHERS.IDW },
    { pattern: /high\s*strangeness/i, series: "High Strangeness", publisher: PUBLISHERS.ONI_PRESS },
    { pattern: /mad\s*max\s*fury\s*road/i, series: "Mad Max Fury Road", publisher: PUBLISHERS.VERTIGO },
    { pattern: /supernatural/i, series: "Supernatural", publisher: PUBLISHERS.DYNAMITE },
];
